config/routes.rb
Money::Application.routes.draw do
  resources :records

  resources :sheets do
    member do
      get 'income'
      get 'expense'
      get 'pending_income'
      get 'pending_expense'
      get 'record_search'
    end

    collection do
      get 'search'
    end
  end

  root :to => 'sheets#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
  Income = 1
  Expense = 0
  Pending_income = 3
  Pending_expense = 2
  
  attr_accessible :amount, :description, :sheet_id, :time, :typenum
  validates :amount, :description, presence: true
  belongs_to :sheet
  
  def type
    string = income ? "Income" : "Expense"
    string = "Pending " + string if pending
    string
  end
  
  def typenum=num
    num = num.to_i
    self.income = (num & 1) > 0
    self.pending = (num & 2) > 0
  end

  def typenum
    number = 0
    number += self.income ? 1 : 0
    number += self.pending ? 2 : 0
    number
  end

  def currency
    sheet.currency
  end
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  belongs_to :sheet
  has_many :sheets, dependent: :destroy
  has_many :records, dependent: :destroy, order: 'time desc'
  attr_accessible :currency, :name, :sheet_id
  validates :currency, :name, presence: true
  
  def income
    records.where(pending: false, income: true).sum(:amount)
  end
  
  def expense
    records.where(pending: false, income: false).sum(:amount)
  end
  
  def pending_income
    records.where(pending: true, income: true).sum(:amount)
  end
  
  def pending_expense
    records.where(pending: true, income: false).sum(:amount)
  end
  
  def balance
    income - expense
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.json
  def index
    @records = Record.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new
    @sheet_id = params[:sheet_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
    @sheet_id = @record.sheet.id
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record.sheet, notice: 'Record was successfully created.' }
        format.json { render json: @record, status: :created, location: @record }
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record.sheet, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_filter :ransack_object_init, only: [:index, :search]
  before_filter :record_ransack_object_init, only:[:show, :income, :expense, :pending_income, :pending_expense, :record_search]

  # GET /sheets
  # GET /sheets.json
  def index
    @sheets = Sheet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sheets }
    end
  end

  # GET /sheets/1
  # GET /sheets/1.json
  def show
    @sheet = Sheet.find(params[:id])
    @records = @sheet.records
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sheet }
    end
  end

  # GET /sheets/new
  # GET /sheets/new.json
  def new
    @sheet = Sheet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sheet }
    end
  end

  # GET /sheets/1/edit
  def edit
    @sheet = Sheet.find(params[:id])
  end

  # POST /sheets
  # POST /sheets.json
  def create
    @sheet = Sheet.new(params[:sheet])

    respond_to do |format|
      if @sheet.save
        format.html { redirect_to sheets_path, notice: "Sheet #{@sheet.name} was successfully created." }
        format.json { render json: @sheet, status: :created, location: @sheet }
      else
        format.html { render action: "new" }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sheets/1
  # PUT /sheets/1.json
  def update
    @sheet = Sheet.find(params[:id])

    respond_to do |format|
      if @sheet.update_attributes(params[:sheet])
        format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheets/1
  # DELETE /sheets/1.json
  def destroy
    @sheet = Sheet.find(params[:id])
    sheet_name = @sheet.name
    @sheet.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: "Sheet #{sheet_name} was deleted!"}
      format.json { head :no_content }
    end
  end

  def income
    @sheet = Sheet.find(params[:id])
    @records = @sheet.records.where(pending: false, income: true)
    render :show
  end

  def expense
    @sheet = Sheet.find(params[:id])
    @records = @sheet.records.where(pending: false, income: false)
    render :show
  end

  def pending_income
    @sheet = Sheet.find(params[:id])
    @records = @sheet.records.where(pending: true, income: true)
    render :show
  end

  def pending_expense
    @sheet = Sheet.find(params[:id])
    @records = @sheet.records.where(pending: true, income: false)
    render :show
  end

  def search
    @sheets = @q.result
    render :index
  end

  def record_search
    @sheet = Sheet.find(params[:id])
    @records = @q.result.where(sheet_id: @sheet.id)
    render :show
  end

  private

  def ransack_object_init
     @q = Sheet.search(params[:q])
  end

  def record_ransack_object_init
    @q = Record.search(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Money"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Money
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
        .span9
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/records/_form.html.haml
= form_for(@record) do |f|
  - if @record.errors.any?
    #error_explanation
      %h2= "#{pluralize(@record.errors.count, "error")} prohibited this record from being saved:"
      %ul
        - @record.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_area :description, class: "decent"
  .field
    = f.label :amount
    = f.text_field :amount
  
  .row-fluid
    .span1
      %label.radio
        = f.radio_button :typenum, Record::Income
        Income

    .span1
      %label.radio
        = f.radio_button :typenum, Record::Expense
        Expense

    .span1
      %label.radio
        = f.radio_button :typenum, Record::Pending_income
        Pending Income
    
    .span1
      %label.radio
        = f.radio_button :typenum, Record::Pending_expense
        Pending Expense
  .field
    = f.label :time
    = f.datetime_select :time
  .actions
    = hidden_field_tag "record[sheet_id]", @sheet_id
    = f.submit 'Save', class: "btn"

app/views/records/_record.html.haml
%tr
  %td=record.description
  %td=record.time
  %td=record.type
  %td
    =record.sheet.currency
    =record.amount
    \/-
  %td
    =link_to "Edit", edit_record_path(record), class: "btn btn-mini"
    =link_to "Delete", record, method: :delete, class: "btn btn-mini", confirm: "Do you truly want to delete record?"

app/views/records/edit.html.haml
%h1 Editing record

= render 'form'

= link_to 'Show', @record
\|
= link_to 'Back', records_path

app/views/records/index.html.haml
%h1 Listing records

%table
  %tr
    %th Description
    %th Amount
    %th Income
    %th Pending
    %th
    %th
    %th

  - @records.each do |record|
    %tr
      %td= record.description
      %td= record.amount
      %td= record.income
      %td= record.pending
      %td= link_to 'Show', record
      %td= link_to 'Edit', edit_record_path(record)
      %td= link_to 'Destroy', record, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Record', new_record_path

app/views/records/new.html.haml
%h1 New record

= render 'form'

app/views/records/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @record.description
%p
  %b Amount:
  = @record.amount
%p
  %b Income:
  = @record.income
%p
  %b Pending:
  = @record.pending

= link_to 'Edit', edit_record_path(@record)
\|
= link_to 'Back', records_path

app/views/sheets/_form.html.haml
= form_for @sheet do |f|
  - if @sheet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sheet.errors.count, "error")} prohibited this sheet from being saved:"
      %ul
        - @sheet.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :currency
    = f.text_field :currency
  .field
    = f.label :sheet_id
    = f.text_field :sheet_id
  .actions
    = f.submit 'Save', class: "btn"

app/views/sheets/_record_search_form.html.haml
=search_form_for(@q, url:{action: :record_search, id: @sheet.id}, html:{class: "form-search"}) do |f|
  =f.text_field :description_cont, class: "search-query", placeholder: "Search Records"
  =f.submit "Search", class: "btn"

app/views/sheets/_search_form.html.haml
=search_form_for(@q, url:{action: :search}, html:{class: "form-search"}) do |f|
  =f.text_field :name_cont, class: "search-query", placeholder: "Search Sheets"
  =f.submit "Search", class: "btn"

app/views/sheets/_sheet.html.haml
%tr
  %td=sheet.name
  %td
    =sheet.currency
    =sheet.income
    \/-
  %td
    =sheet.currency
    =sheet.expense
    \/-
  %td
    =sheet.currency
    =sheet.pending_income
    \/-
  %td
    =sheet.currency
    =sheet.pending_expense
    \/-
  %td
    =sheet.currency
    =sheet.balance
    \/-
  %td
    =link_to "View", sheet, class: "btn btn-mini"
    =link_to "Edit", edit_sheet_path(sheet), class: "btn btn-mini"
    =link_to "Delete", sheet, method: :delete, class: "btn btn-mini", confirm: "Do you really want to delete #{sheet.name}?"

app/views/sheets/edit.html.haml
%h1 Editing sheet

= render 'form'

= link_to 'Show', @sheet
\|
= link_to 'Back', sheets_path

app/views/sheets/index.html.haml
.row-fluid
  .span4=render partial: 'search_form'
  .span3=link_to "New Sheet", new_sheet_path, class: "btn btn-primary"

%table.table
  %thead
    %tr
      %th Sheet
      %th Income
      %th Expense
      %th Pending Income
      %th Pending Expense
      %th Balance
      %th Action
  %tbody
    =render @sheets

app/views/sheets/new.html.haml
%h1 New sheet

= render 'form'

= link_to 'Back', sheets_path

app/views/sheets/show.html.haml
.row-fluid
  .well.bottom_pad50
    .span2
      %b Income
      %br
      = link_to @sheet.income, income_sheet_path(@sheet)
    .span2
      %b Expense
      %br
      = link_to @sheet.expense, expense_sheet_path(@sheet)
    .span2
      %b Pending Income
      %br
      = link_to @sheet.pending_income, pending_income_sheet_path(@sheet)
    .span2
      %b Pending Expense
      %br
      = link_to @sheet.pending_expense, pending_expense_sheet_path(@sheet)
    .span2
    .span2
      %b Balance
      %br
      = link_to @sheet.balance, @sheet

.row-fluid
  .span4=render partial: 'record_search_form'
  .span3=link_to "New Record", {action: :new, controller: :records, sheet_id: @sheet.id}, class: "btn btn-primary"

%table.table
  %thead
    %tr
      %th Description
      %th Date - Time
      %th Type
      %th Amount
      %th Action
  %tbody
    =render @records